### ISSUE TITLE
فروشگاه ارسال کننده اطلاعات قابل شناسايي نيست

### ISSUE THREAD

**Issue by hossienikiu** [pepco-api/php-rest-sdk#1]
Exception
فروشگاه ارسال کننده اطلاعات قابل شناسايي نيست.

• اگر مجددا با خطاي نامبرده مواجه شديد
لطفا نسبت به تعويض توليد کليد عمومي و
خصوصي خود اقدام نماييد.

این کار چگونه باید انجام شود؟

**Comment by rseyf** [comment]
لطفا از طریق تیکت در [پنل پشتیبانی](https://my.pep.co.ir/) شرکت اقدام کنید.
